name: media
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # pdf
  flutter_pdfview: ^1.3.1
  pdf: ^3.10.4

  # path
  path_provider: ^2.1.1
  path: ^1.8.3
  file_picker: ^5.5.0

  # screen recording prevention
  flutter_windowmanager: ^0.2.0

  # audio
  permission_handler: ^11.0.0
  cached_network_image: ^3.3.0
  audio_video_progress_bar: ^2.0.0
  audioplayers: ^5.1.0
  just_audio_background: ^0.0.1-beta.10
  just_audio: ^0.9.35
  rxdart: ^0.27.7

  # video
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
